export const VEHICLE_BRANDS: Record<string, string[]> = {
  'Alfa Romeo': ['147', '156', '159', 'Giulia', 'Giulietta', 'MiTo', 'Stelvio'],
  'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'RS3', 'RS4', 'RS6', 'S3', 'S4', 'TT'],
  'BMW': ['M2', 'M3', 'M4', 'M5', 'Serie 1', 'Serie 2', 'Serie 3', 'Serie 4', 'Serie 5', 'Serie 7', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7'],
  'BYD': ['Atto 3', 'Dolphin', 'Han', 'Seal', 'Tang'],
  'Chevrolet': ['Agile', 'Blazer', 'Captiva', 'Classic', 'Colorado', 'Corsa', 'Corsa 2', 'Cruze', 'Equinox', 'Montana', 'Onix', 'Onix Plus', 'S10', 'Spin', 'Tracker', 'Trailblazer', 'Trax'],
  'Chery': ['Arrizo 5', 'Arrizo 6', 'Tiggo 2', 'Tiggo 4', 'Tiggo 7', 'Tiggo 8'],
  'Citroën': ['Berlingo', 'C-Elysée', 'C3', 'C3 Aircross', 'C4', 'C4 Cactus', 'C4 Lounge', 'C5 Aircross', 'Jumper', 'Spacetourer', 'Xsara', 'Xsara Picasso'],
  'Dodge': ['Challenger', 'Charger', 'Durango', 'Journey', 'Neon', 'Ram 700'],
  'Fiat': ['Argo', 'Bravo', 'Cronos', 'Doblò', 'Ducato', 'Fastback', 'Fiorino', 'Linea', 'Palio', 'Pulse', 'Punto', 'Siena', 'Strada', 'Toro', 'Uno'],
  'Ford': ['Bronco Sport', 'Ecosport', 'Edge', 'Escape', 'Explorer', 'F-150', 'Fiesta', 'Focus', 'Fusion', 'Ka', 'Ka+', 'Kuga', 'Maverick', 'Mondeo', 'Mustang', 'Ranger', 'Territory'],
  'GAC': ['GS3', 'GS4', 'GS5', 'GS8'],
  'GWM': ['Haval H6', 'Ora 3', 'Poer'],
  'Honda': ['Accord', 'City', 'Civic', 'CR-V', 'Fit', 'HR-V', 'Jazz', 'Pilot', 'WR-V'],
  'Hyundai': ['Accent', 'Creta', 'Elantra', 'Getz', 'HB20', 'i20', 'i30', 'Ioniq 5', 'Kona', 'Santa Cruz', 'Santa Fe', 'Tucson', 'Venue'],
  'Jeep': ['Cherokee', 'Compass', 'Gladiator', 'Grand Cherokee', 'Renegade', 'Wrangler'],
  'Kia': ['Carnival', 'Cerato', 'EV6', 'Niro', 'Picanto', 'Rio', 'Seltos', 'Sorento', 'Soul', 'Sportage', 'Stinger'],
  'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Freelander', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar'],
  'Mercedes-Benz': ['CLA', 'Clase A', 'Clase B', 'Clase C', 'Clase E', 'Clase G', 'Clase S', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'Sprinter', 'Vito'],
  'MG': ['HS', 'ZS', 'ZS EV'],
  'Mitsubishi': ['ASX', 'Eclipse Cross', 'L200', 'Lancer', 'Montero', 'Montero Sport', 'Outlander', 'Pajero'],
  'Nissan': ['Frontier', 'Kicks', 'Leaf', 'March', 'Murano', 'Pathfinder', 'Patrol', 'Qashqai', 'Sentra', 'Tiida', 'Versa', 'X-Trail'],
  'Peugeot': ['2008', '206', '207', '208', '3008', '301', '307', '308', '408', '5008', '508', 'Boxer', 'Expert', 'Partner', 'Rifter'],
  'Porsche': ['718', '911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
  'RAM': ['1500', '2500', '700', 'ProMaster'],
  'Renault': ['Alaskan', 'Captur', 'Clio', 'Duster', 'Fluence', 'Kadjar', 'Kangoo', 'Koleos', 'Kwid', 'Logan', 'Master', 'Megane', 'Oroch', 'Sandero', 'Stepway', 'Symbol', 'Trafic', 'Zoe'],
  'SEAT': ['Arona', 'Ateca', 'Ibiza', 'Leon', 'Tarraco'],
  'Skoda': ['Fabia', 'Karoq', 'Kodiaq', 'Octavia', 'Scala', 'Superb'],
  'Subaru': ['Forester', 'Impreza', 'Legacy', 'Outback', 'XV'],
  'Suzuki': ['Ignis', 'Jimny', 'Swift', 'SX4', 'Vitara'],
  'Toyota': ['Camry', 'Corolla', 'Corolla Cross', 'Etios', 'FJ Cruiser', 'Fortuner', 'Hilux', 'Land Cruiser', 'Land Cruiser Prado', 'Prius', 'RAV4', 'Rush', 'SW4', 'Yaris'],
  'Volkswagen': ['Amarok', 'Fox', 'Gol', 'Golf', 'Jetta', 'Nivus', 'Passat', 'Polo', 'Saveiro', 'Suran', 'T-Cross', 'Taos', 'Tiguan', 'Touareg', 'Up!', 'Vento', 'Virtus'],
  'Volvo': ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90'],
}

export const BRAND_NAMES = Object.keys(VEHICLE_BRANDS).sort()
